### PR TITLE
Feature/pass data through app

### PR DESCRIPTION
**Pull request by tomdoughty**
## Description
Persist state through the app
Go back to questions from summary
Branch questions

## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] CHANGELOG entry

### CODE REVIEW

**Comment by davidhunter08** [comment]
Hey @tomdoughty, what code fixed the issue for https://github.com/nhsuk/nhsuk-prototype-kit/issues/108?

**Comment by tomdoughty** [comment]
> Hey @tomdoughty, what code fixed the issue for [nhsuk/nhsuk-prototype-kit#108](https://github.com/nhsuk/nhsuk-prototype-kit/issues/108)?

@davidhunter08 pretty much this :) https://github.com/nhsuk/citizen-survey-tool-prototype/pull/2/commits/c9c09bcbaf779c444b1eb766914243d619cbda2b

**Comment by davidhunter08** [comment]
> > Hey @tomdoughty, what code fixed the issue for [nhsuk/nhsuk-prototype-kit#108](https://github.com/nhsuk/nhsuk-prototype-kit/issues/108)?
> 
> @davidhunter08 pretty much this :) [c9c09bc](https://github.com/nhsuk/citizen-survey-tool-prototype/commit/c9c09bcbaf779c444b1eb766914243d619cbda2b)

🙌

**Comment by tomdoughty** [comment]
> > > Hey @tomdoughty, what code fixed the issue for [nhsuk/nhsuk-prototype-kit#108](https://github.com/nhsuk/nhsuk-prototype-kit/issues/108)?
> > 
> > 
> > @davidhunter08 pretty much this :) [c9c09bc](https://github.com/nhsuk/citizen-survey-tool-prototype/commit/c9c09bcbaf779c444b1eb766914243d619cbda2b)
> 
> 🙌

Actually found an easier way which works for now... I will put the full description of why on the fix but if you add `[]` at the end of the `name` on the nunjucks template then it works. 
[Blog post that helped me out](https://dev.niamurrell.com/reference/2019-01-31-checkboxes-in-forms-with-body-parser/)

**Comment by davidhunter08** [comment]
Thanks for your help on this @thomashdoughty. Most of the work has been implemented so I'm going to close this pull request.

**Pull request closed without merging**
